[package]
name = "i-face"
version = "0.1.0"
authors = ["keiSunagawa <kei.sunagawa@mvrck.co.jp>"]
edition = "2018"

[dependencies]
rustyline = { git = "https://github.com/kkawakam/rustyline", branch = "master" }
